### ISSUE TITLE
Terminals crashes on start

### ISSUE THREAD

**Issue by validstorm1** [OliverKohlDSc/Terminals#43]
Two errors follow the crash
Application: Terminals.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(System.DirectoryServices.DirectoryEntry, System.String)
   at System.DirectoryServices.PropertyCollection.get_Item(System.String)
   at Kohl.Framework.Info.UserInfo.get_UserName()
   at Kohl.Framework.Info.HumanReadableInfo.ToString()
   at Kohl.Framework.Info.HumanReadableInfo.ToLog()
   at Terminals.Program.<LogGeneralProperties>m__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

And 
Faulting application name: Terminals.exe, version: 4.9.1.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.14393.953, time stamp: 0x58ba586d
Exception code: 0xe0434352
Fault offset: 0x000da882
Faulting process id: 0x49bc
Faulting application start time: 0x01d2afb23c9048a9
Faulting application path: C:\Program Files (x86)\Terminals\Terminals.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d54f6ed0-397f-41ee-880b-9a45680730c7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by OliverKohlDSc** [comment]
Many thanks for reporting this issue!
