### ISSUE TITLE
Terminals keeps crashing after start

### ISSUE THREAD

**Issue by lukasvosyka** [OliverKohlDSc/Terminals#54]
Hi,
I installed Terminals because I really liked it. I was using 4.0 before, but after installing this version it keeps crashing right after the start.

This is what the log says:

INFO  2017-05-21 13:38:50,784    84ms config                 Info               - -------------------------------Terminals started. Version: 4.9.1.0, Date: 16/04/2017 06:05:55-------------------------------
INFO  2017-05-21 13:38:50,802   102ms config                 LoadDnsServers     - Precaching DNS servers
WARN  2017-05-21 13:38:50,841   141ms config                 eDefaultConfigFile - Using a new plain Terminals configuration file.
INFO  2017-05-21 13:38:50,883   183ms config                 teConfigFileBackup - Configuration file backup has been created successfully.
INFO  2017-05-21 13:39:03,804 13104ms config                 SaveHistory        - History saved. Duration:17 ms
INFO  2017-05-21 13:39:03,805 13105ms config                 LoadHistory        - Load History Duration: 20 ms
WARN  2017-05-21 13:39:03,841 13141ms config                 Create             - The connection to the terminals database will be ignored.
INFO  2017-05-21 13:39:03,841 13141ms config                 GroupByDate        - Grouping history items by date.
INFO  2017-05-21 13:39:04,113 13413ms config                 ogNonAdministrator - Terminals is running in non-admin mode.
INFO  2017-05-21 13:39:05,700 15000ms config                 Info               - Received release date "18/11/2016 12:15:31 +01:00" from the TerminalsBuildDate file stored on GitHub in Terminals 4.9.2.0
INFO  2017-05-21 13:39:06,015 15316ms config                 Info               - Received release date "16/04/2017 06:05:55 +02:00" from the TerminalsBuildDate file stored on GitHub in Terminals 4.9.1.0
ERROR 2017-05-21 13:39:12,997 22298ms config                 LoadDnsServers     - The DNS server lookup failed.
System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException: Current security context is not associated with an Active Directory domain or forest.
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetLoggedOnDomain()
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isRootDomain()
   at System.DirectoryServices.ActiveDirectory.Forest.GetForest(DirectoryContext context)
   at Terminals.Network.DNS.AdapterInfo.LoadDnsServers()

**Comment by cpmcgrath** [comment]
The exception mentioned is caught, logged, and then continued from. I doubt it's where the crash is happening. Considering that it seems to be Active Directory related I think this is most likely the same as #43 - You could confirm this by looking at the exception in the Windows Event Viewer.

#43 This has been resolved in the "future" branch. 
@OliverKohlDSc Could we make a new pre-release?
